// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioBlogWebApp.Models;

namespace PortfolioBlogWebApp.Migrations
{
    [DbContext(typeof(MyProjectsDbContext))]
    partial class MyProjectsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PortfolioBlogWebApp.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProjectCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProjectDateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ProjectDateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLogoFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectLongDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectShortDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
